//! Layers: everything that can appear in a scene.
//!
//! A layer is **data** — a serde tree with a start time, a duration, an
//! entrance and an exit. It is not a closure and not a component, which is what
//! lets the same description be written in Rust, loaded from JSON, generated by
//! a program, or (later) emitted by a tool over MCP without any of them being a
//! special case.
//!
//! Three of these exist because the captain named them:
//! [`Content::Counter`] (a number that ticks in time with the footage),
//! [`Content::Callout`] (a label that points at something) and
//! [`Content::PullUp`] (take a piece of what is on screen, dim the rest, and
//! bring it forward, enlarged and annotated).

use crate::assets::{AssetStore, ClipLoop};
use crate::camera::Camera;
use crate::canvas::Canvas;
use crate::color::{Color, Paint};
use crate::ease::Easing;
use crate::geom::{Anchor, Fit, Rect};
use crate::motion::{Motion, MotionState};
use crate::text::{Align, FontDb, GlyphTransform, Plate, Shadow, TextLayout, TextStyle};
use crate::time::Time;
use anyhow::Result;
use serde::{Deserialize, Serialize};

/// What the renderer needs to draw a layer.
pub struct RenderCtx<'a> {
    pub assets: &'a AssetStore,
    pub fonts: &'a FontDb,
    /// The frame, in pixels.
    pub frame: Rect,
    pub fps: f64,
}

/// Where a layer sits in the frame.
///
/// Written as a bare word for the common cases — `"centre"`, `"bottom-left"`,
/// `"full"` — and as an object when it needs numbers. An untagged
/// representation rather than a tagged one, because `"placement": "centre"`
/// is what an author wants to type and `{"at":"anchored","anchor":"centre"}`
/// is not.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(from = "PlacementRepr", into = "PlacementRepr")]
pub enum Placement {
    /// Fill the whole frame.
    Full,
    /// Pinned to an anchor, `pad` in from the edges.
    Anchored { anchor: Anchor, pad: f64 },
    /// An explicit rect in frame pixels.
    Rect { x: f64, y: f64, w: f64, h: f64 },
    /// A rect given in fractions of the frame, so it survives a resolution
    /// change. This is the one to reach for.
    Frac { fx: f64, fy: f64, fw: f64, fh: f64 },
}

/// The wire form of [`Placement`].
#[derive(Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlacementRepr {
    /// `"full"`, or any anchor name.
    Word(String),
    Anchored {
        anchor: Anchor,
        #[serde(default = "default_pad")]
        pad: f64,
    },
    Frac { fx: f64, fy: f64, fw: f64, fh: f64 },
    Rect { x: f64, y: f64, w: f64, h: f64 },
}

impl From<PlacementRepr> for Placement {
    fn from(r: PlacementRepr) -> Placement {
        match r {
            PlacementRepr::Word(w) => {
                if w.eq_ignore_ascii_case("full") {
                    Placement::Full
                } else {
                    match serde_json::from_value::<Anchor>(serde_json::Value::String(w)) {
                        Ok(a) => Placement::Anchored { anchor: a, pad: default_pad() },
                        // An unrecognised word is a full-frame placement rather
                        // than a hard error: a typo should cost you a look, not
                        // a render.
                        Err(_) => Placement::Full,
                    }
                }
            }
            PlacementRepr::Anchored { anchor, pad } => Placement::Anchored { anchor, pad },
            PlacementRepr::Frac { fx, fy, fw, fh } => Placement::Frac { fx, fy, fw, fh },
            PlacementRepr::Rect { x, y, w, h } => Placement::Rect { x, y, w, h },
        }
    }
}

impl From<Placement> for PlacementRepr {
    fn from(p: Placement) -> PlacementRepr {
        match p {
            Placement::Full => PlacementRepr::Word("full".into()),
            Placement::Anchored { anchor, pad } => PlacementRepr::Anchored { anchor, pad },
            Placement::Rect { x, y, w, h } => PlacementRepr::Rect { x, y, w, h },
            Placement::Frac { fx, fy, fw, fh } => PlacementRepr::Frac { fx, fy, fw, fh },
        }
    }
}

fn default_pad() -> f64 {
    72.0
}

impl Default for Placement {
    fn default() -> Self {
        Placement::Full
    }
}

impl Placement {
    pub fn anchored(a: Anchor) -> Self {
        Placement::Anchored { anchor: a, pad: default_pad() }
    }

    pub fn frac(fx: f64, fy: f64, fw: f64, fh: f64) -> Self {
        Placement::Frac { fx, fy, fw, fh }
    }

    /// Resolve to a box in the frame. `natural` is the content's own size,
    /// used by [`Placement::Anchored`].
    pub fn resolve(&self, frame: &Rect, natural: (f64, f64)) -> Rect {
        match *self {
            Placement::Full => *frame,
            Placement::Anchored { anchor, pad } => anchor.place(frame, natural.0, natural.1, pad),
            Placement::Rect { x, y, w, h } => Rect::new(x, y, w, h),
            Placement::Frac { fx, fy, fw, fh } => {
                Rect::new(frame.w * fx, frame.h * fy, frame.w * fw, frame.h * fh)
            }
        }
    }
}

/// A number that animates.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CounterSpec {
    pub from: f64,
    pub to: f64,
    /// How long the count takes. Shorter than the layer means it lands early
    /// and holds, which is usually what a milestone wants.
    pub over: Time,
    #[serde(default)]
    pub easing: Easing,
    #[serde(default)]
    pub decimals: u8,
    /// Group thousands with a thin space.
    #[serde(default = "yes")]
    pub group: bool,
    #[serde(default)]
    pub prefix: String,
    #[serde(default)]
    pub suffix: String,
}

fn yes() -> bool {
    true
}

impl CounterSpec {
    pub fn new(from: f64, to: f64, over: impl Into<Time>) -> Self {
        CounterSpec {
            from,
            to,
            over: over.into(),
            easing: Easing::OutExpo,
            decimals: 0,
            group: true,
            prefix: String::new(),
            suffix: String::new(),
        }
    }

    pub fn suffix(mut self, s: impl Into<String>) -> Self {
        self.suffix = s.into();
        self
    }

    pub fn prefix(mut self, s: impl Into<String>) -> Self {
        self.prefix = s.into();
        self
    }

    pub fn decimals(mut self, d: u8) -> Self {
        self.decimals = d;
        self
    }

    pub fn value_at(&self, t: f64) -> f64 {
        let d = self.over.as_secs();
        let p = if d <= 0.0 { 1.0 } else { (t / d).clamp(0.0, 1.0) };
        self.from + (self.to - self.from) * self.easing.apply(p)
    }

    pub fn text_at(&self, t: f64) -> String {
        let v = self.value_at(t);
        let body = if self.decimals == 0 {
            let n = v.round() as i64;
            if self.group { group_thousands(&n.abs().to_string(), n < 0) } else { n.to_string() }
        } else {
            let s = format!("{:.*}", self.decimals as usize, v.abs());
            if self.group {
                let (int, frac) = s.split_once('.').unwrap_or((s.as_str(), ""));
                let g = group_thousands(int, v < 0.0);
                if frac.is_empty() { g } else { format!("{g}.{frac}") }
            } else {
                format!("{:.*}", self.decimals as usize, v)
            }
        };
        format!("{}{}{}", self.prefix, body, self.suffix)
    }
}

/// A narrow no-break space between thousands: it reads as a group without the
/// comma fighting the tabular alignment.
fn group_thousands(digits: &str, negative: bool) -> String {
    let mut out = String::new();
    let n = digits.len();
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (n - i) % 3 == 0 {
            out.push('\u{202f}');
        }
        out.push(c);
    }
    if negative { format!("-{out}") } else { out }
}

/// A label that points at something.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CalloutSpec {
    /// What it points at, in fractions of the frame.
    pub target: (f64, f64),
    /// Where the label sits, in fractions of the frame.
    pub label_at: (f64, f64),
    pub text: String,
    #[serde(default)]
    pub detail: Option<String>,
    #[serde(default = "accent_default")]
    pub accent: Color,
    /// Radius of the ring drawn on the target.
    #[serde(default = "ring_default")]
    pub ring: f64,
}

fn accent_default() -> Color {
    Color::rgb(255, 209, 71)
}

fn ring_default() -> f64 {
    26.0
}

/// Take a region of what is already on screen and bring it forward.
///
/// This is the explainer idiom the captain described: highlight, enlarge, pull
/// forward, annotate. It reads the canvas beneath it, so it works over *any*
/// layer — a map, a video, a chart — without knowing what that layer was.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PullUpSpec {
    /// The region to lift, in fractions of the frame.
    pub region: (f64, f64, f64, f64),
    /// Where it lands, in fractions of the frame. Its aspect ratio is kept.
    #[serde(default)]
    pub to: Option<(f64, f64, f64, f64)>,
    /// How much the rest of the frame is dimmed, 0..1.
    #[serde(default = "dim_default")]
    pub dim: f64,
    #[serde(default = "radius_default")]
    pub radius: f64,
    #[serde(default = "border_default")]
    pub border: Color,
    #[serde(default = "border_w_default")]
    pub border_width: f64,
    #[serde(default)]
    pub label: Option<String>,
    /// Draw a line from where it came from to where it went.
    #[serde(default = "yes")]
    pub tether: bool,
}

fn dim_default() -> f64 {
    0.62
}

fn radius_default() -> f64 {
    14.0
}

fn border_default() -> Color {
    Color::WHITE
}

fn border_w_default() -> f64 {
    3.0
}

/// The content of a layer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum Content {
    /// A flat colour.
    Solid { colour: Color },
    /// A linear gradient across the placement box.
    Gradient { stops: Vec<(f64, Color)>, #[serde(default)] angle: f64 },
    /// A darkening gradient from an edge, so text over footage stays legible.
    Scrim {
        #[serde(default = "scrim_h")]
        height: f64,
        #[serde(default = "scrim_s")]
        strength: f64,
        #[serde(default = "black_c")]
        colour: Color,
    },
    /// A still image, optionally seen through a camera move.
    Still {
        asset: String,
        #[serde(default)]
        fit: Fit,
        #[serde(default)]
        camera: Option<Camera>,
    },
    /// A video clip.
    Clip {
        asset: String,
        #[serde(default)]
        fit: Fit,
        /// Seconds into the clip at which the layer's own time zero sits.
        #[serde(default)]
        start: Time,
        #[serde(default)]
        mode: ClipLoop,
        /// Cap the decode width. Keeps a 4K source from being held in memory
        /// when it appears as a thumbnail.
        #[serde(default = "clip_max_w")]
        max_width: u32,
        /// Round the clip's corners, and optionally frame it.
        #[serde(default)]
        radius: f64,
        #[serde(default)]
        border: Option<(Color, f64)>,
        #[serde(default)]
        shadow: Option<Shadow>,
    },
    /// A block of text.
    Text {
        text: String,
        #[serde(default)]
        style: TextStyle,
        /// Wrap to this fraction of the placement box's width.
        #[serde(default = "one")]
        wrap: f64,
        /// Shrink to fit the placement box rather than overflowing.
        #[serde(default)]
        fit: bool,
    },
    /// A title and an optional standfirst, styled as a pair.
    Title {
        text: String,
        #[serde(default)]
        subtitle: Option<String>,
        #[serde(default)]
        style: Option<TextStyle>,
        #[serde(default)]
        subtitle_style: Option<TextStyle>,
    },
    /// The broadcast lower-third: a plate, a headline and a strapline.
    LowerThird {
        text: String,
        #[serde(default)]
        detail: Option<String>,
        #[serde(default = "accent_default")]
        accent: Color,
        #[serde(default)]
        style: Option<TextStyle>,
        #[serde(default)]
        detail_style: Option<TextStyle>,
    },
    /// A number that counts.
    ///
    /// `count` is nested rather than flattened because a counter's `from` is a
    /// *value* and a layer's `from` is a *time*; flattening them into one
    /// object would put two different meanings on one word.
    Counter {
        #[serde(rename = "count")]
        spec: CounterSpec,
        #[serde(default)]
        label: Option<String>,
        #[serde(default)]
        style: Option<TextStyle>,
        #[serde(default)]
        label_style: Option<TextStyle>,
    },
    /// A label with a leader line pointing at a place in the frame.
    Callout {
        #[serde(flatten)]
        spec: CalloutSpec,
        #[serde(default)]
        style: Option<TextStyle>,
        #[serde(default)]
        detail_style: Option<TextStyle>,
    },
    /// Lift a region of the frame, enlarge it, annotate it.
    PullUp {
        #[serde(flatten)]
        spec: PullUpSpec,
        #[serde(default)]
        style: Option<TextStyle>,
    },
}

impl Content {
    /// Where this kind of thing goes when nobody says otherwise.
    ///
    /// A lower-third belongs at the bottom left and a counter at the top
    /// right; those are conventions, not preferences, and a toolset that makes
    /// you restate them every time is one you fight. The Rust builders set
    /// these too, so a film written in JSON and the same film written in Rust
    /// land in the same place.
    pub fn default_placement(&self) -> Placement {
        use Anchor::*;
        match self {
            Content::Title { .. } | Content::Text { .. } => {
                Placement::Anchored { anchor: Centre, pad: default_pad() }
            }
            Content::LowerThird { .. } => Placement::Anchored { anchor: BottomLeft, pad: 96.0 },
            Content::Counter { .. } => Placement::Anchored { anchor: TopRight, pad: default_pad() },
            // These carry their own coordinates, so the frame is the box.
            Content::Solid { .. }
            | Content::Gradient { .. }
            | Content::Scrim { .. }
            | Content::Still { .. }
            | Content::Clip { .. }
            | Content::Callout { .. }
            | Content::PullUp { .. } => Placement::Full,
        }
    }
}

fn scrim_h() -> f64 {
    0.42
}

fn scrim_s() -> f64 {
    0.85
}

fn black_c() -> Color {
    Color::BLACK
}

fn clip_max_w() -> u32 {
    1920
}

fn one() -> f64 {
    1.0
}

/// A layer: content, when it is on screen, and how it arrives and leaves.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Layer {
    #[serde(flatten)]
    pub content: Content,
    /// When it appears, measured from the start of its scene.
    #[serde(default)]
    pub from: Time,
    /// How long for. `None` means "until the scene ends".
    #[serde(default)]
    pub duration: Option<Time>,
    /// `None` means "wherever this kind of content belongs" — see
    /// [`Content::default_placement`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placement: Option<Placement>,
    #[serde(default)]
    pub enter: Option<Motion>,
    #[serde(default)]
    pub exit: Option<Motion>,
    /// A constant multiplier on top of any motion.
    #[serde(default = "one")]
    pub opacity: f64,
    /// Higher draws later. Layers with equal z keep their declared order.
    #[serde(default)]
    pub z: i32,
}

impl Layer {
    pub fn new(content: Content) -> Self {
        Layer {
            content,
            from: Time::ZERO,
            duration: None,
            placement: None,
            enter: None,
            exit: None,
            opacity: 1.0,
            z: 0,
        }
    }

    // ---- constructors: the vocabulary a film is written in ---------------

    pub fn solid(colour: Color) -> Self {
        Layer::new(Content::Solid { colour })
    }

    pub fn gradient(stops: Vec<(f64, Color)>, angle: f64) -> Self {
        Layer::new(Content::Gradient { stops, angle })
    }

    /// A darkening gradient up from the bottom edge.
    pub fn scrim() -> Self {
        Layer::new(Content::Scrim { height: scrim_h(), strength: scrim_s(), colour: Color::BLACK })
    }

    pub fn still(asset: impl Into<String>) -> Self {
        Layer::new(Content::Still { asset: asset.into(), fit: Fit::Cover, camera: None })
    }

    /// A still seen through a camera move — the headline capability.
    pub fn camera(asset: impl Into<String>, camera: Camera) -> Self {
        Layer::new(Content::Still { asset: asset.into(), fit: Fit::Cover, camera: Some(camera) })
    }

    pub fn clip(asset: impl Into<String>) -> Self {
        Layer::new(Content::Clip {
            asset: asset.into(),
            fit: Fit::Cover,
            start: Time::ZERO,
            mode: ClipLoop::Hold,
            max_width: clip_max_w(),
            radius: 0.0,
            border: None,
            shadow: None,
        })
    }

    pub fn text(text: impl Into<String>) -> Self {
        Layer::new(Content::Text {
            text: text.into(),
            style: TextStyle::default(),
            wrap: 1.0,
            fit: false,
        })
    }

    pub fn title(text: impl Into<String>) -> Self {
        Layer::new(Content::Title {
            text: text.into(),
            subtitle: None,
            style: None,
            subtitle_style: None,
        })
        .entering(Motion::rise(0.7))
    }

    pub fn lower_third(text: impl Into<String>) -> Self {
        Layer::new(Content::LowerThird {
            text: text.into(),
            detail: None,
            accent: accent_default(),
            style: None,
            detail_style: None,
        })
        .entering(Motion::slide_in(0.55, -80.0, 0.0))
        .exiting(Motion::slide_in(0.35, -60.0, 0.0))
    }

    pub fn counter(from: f64, to: f64, over: impl Into<Time>) -> Self {
        Layer::new(Content::Counter {
            spec: CounterSpec::new(from, to, over),
            label: None,
            style: None,
            label_style: None,
        })
        .entering(Motion::rise(0.4))
    }

    pub fn callout(
        text: impl Into<String>,
        target: (f64, f64),
        label_at: (f64, f64),
    ) -> Self {
        Layer::new(Content::Callout {
            spec: CalloutSpec {
                target,
                label_at,
                text: text.into(),
                detail: None,
                accent: accent_default(),
                ring: ring_default(),
            },
            style: None,
            detail_style: None,
        })
        .entering(Motion::fade(0.45))
    }

    /// Lift a region of the frame and bring it forward.
    pub fn pull_up(region: (f64, f64, f64, f64)) -> Self {
        Layer::new(Content::PullUp {
            spec: PullUpSpec {
                region,
                to: None,
                dim: dim_default(),
                radius: radius_default(),
                border: Color::WHITE,
                border_width: border_w_default(),
                label: None,
                tether: true,
            },
            style: None,
        })
        .entering(Motion::new(
            crate::motion::MotionKind::Scale { from: 0.9 },
            0.6,
        ))
    }

    // ---- builders --------------------------------------------------------

    pub fn from(mut self, t: impl Into<Time>) -> Self {
        self.from = t.into();
        self
    }

    pub fn lasting(mut self, d: impl Into<Time>) -> Self {
        self.duration = Some(d.into());
        self
    }

    pub fn placed(mut self, p: Placement) -> Self {
        self.placement = Some(p);
        self
    }

    pub fn at(mut self, a: Anchor) -> Self {
        self.placement = Some(Placement::anchored(a));
        self
    }

    pub fn frac(mut self, fx: f64, fy: f64, fw: f64, fh: f64) -> Self {
        self.placement = Some(Placement::frac(fx, fy, fw, fh));
        self
    }

    /// The placement actually used: the one set, or the content's own default.
    pub fn placement(&self) -> Placement {
        self.placement.clone().unwrap_or_else(|| self.content.default_placement())
    }

    pub fn entering(mut self, m: Motion) -> Self {
        self.enter = Some(m);
        self
    }

    pub fn exiting(mut self, m: Motion) -> Self {
        self.exit = Some(m);
        self
    }

    pub fn opacity(mut self, o: f64) -> Self {
        self.opacity = o;
        self
    }

    pub fn z(mut self, z: i32) -> Self {
        self.z = z;
        self
    }

    pub fn fit(mut self, f: Fit) -> Self {
        match &mut self.content {
            Content::Still { fit, .. } | Content::Clip { fit, .. } => *fit = f,
            _ => {}
        }
        self
    }

    pub fn styled(mut self, s: TextStyle) -> Self {
        match &mut self.content {
            Content::Text { style, .. } => *style = s,
            Content::Title { style, .. }
            | Content::LowerThird { style, .. }
            | Content::Counter { style, .. }
            | Content::Callout { style, .. }
            | Content::PullUp { style, .. } => *style = Some(s),
            _ => {}
        }
        self
    }

    pub fn subtitle(mut self, s: impl Into<String>) -> Self {
        if let Content::Title { subtitle, .. } = &mut self.content {
            *subtitle = Some(s.into());
        }
        self
    }

    pub fn detail(mut self, d: impl Into<String>) -> Self {
        match &mut self.content {
            Content::LowerThird { detail, .. } => *detail = Some(d.into()),
            Content::Callout { spec, .. } => spec.detail = Some(d.into()),
            _ => {}
        }
        self
    }

    pub fn label(mut self, l: impl Into<String>) -> Self {
        match &mut self.content {
            Content::Counter { label, .. } => *label = Some(l.into()),
            Content::PullUp { spec, .. } => spec.label = Some(l.into()),
            _ => {}
        }
        self
    }

    pub fn accent(mut self, c: Color) -> Self {
        match &mut self.content {
            Content::LowerThird { accent, .. } => *accent = c,
            Content::Callout { spec, .. } => spec.accent = c,
            Content::PullUp { spec, .. } => spec.border = c,
            _ => {}
        }
        self
    }

    /// For a clip: round its corners, frame it and drop a shadow — the
    /// treatment an inset needs to sit *on* a background rather than in it.
    pub fn framed(mut self, radius: f64, border: Option<(Color, f64)>) -> Self {
        if let Content::Clip { radius: r, border: b, shadow, .. } = &mut self.content {
            *r = radius;
            *b = border;
            if shadow.is_none() {
                *shadow = Some(Shadow { colour: Color::rgba(0, 0, 0, 160), blur: 30.0, dx: 0.0, dy: 10.0 });
            }
        }
        self
    }

    /// Where the clip's own playhead starts.
    pub fn clip_start(mut self, t: impl Into<Time>) -> Self {
        if let Content::Clip { start, .. } = &mut self.content {
            *start = t.into();
        }
        self
    }

    pub fn looping(mut self) -> Self {
        if let Content::Clip { mode, .. } = &mut self.content {
            *mode = ClipLoop::Loop;
        }
        self
    }

    // ---- timing ----------------------------------------------------------

    /// The span this layer occupies within a scene of `scene_duration`.
    pub fn span(&self, scene_duration: Time) -> crate::time::Span {
        let d = self.duration.unwrap_or(scene_duration - self.from);
        crate::time::Span { start: self.from, duration: d.max(Time::ZERO) }
    }

    /// Whether the layer is on screen at scene time `t`.
    pub fn active_at(&self, t: Time, scene_duration: Time) -> bool {
        let s = self.span(scene_duration);
        // Inclusive of the final instant so the last frame of a scene is not
        // silently empty.
        t >= s.start && t <= s.end()
    }

    /// The whole-layer motion state at scene time `t`.
    ///
    /// The exit wins where the two overlap: a layer told to leave should leave,
    /// even if it was told to arrive slowly.
    pub fn motion_at(&self, t: Time, scene_duration: Time) -> MotionState {
        let span = self.span(scene_duration);
        let local = span.local(t).as_secs();
        let dur = span.duration.as_secs();

        if let Some(exit) = &self.exit {
            let starts_at = dur - exit.duration.as_secs();
            if local >= starts_at {
                return exit.exit_state(local - starts_at);
            }
        }
        match &self.enter {
            Some(enter) => enter.enter_state(local),
            None => MotionState::SETTLED,
        }
    }
}

impl std::ops::Neg for Time {
    type Output = Time;
    fn neg(self) -> Time {
        Time(-self.0)
    }
}

impl Time {
    fn max(self, other: Time) -> Time {
        if self.0 > other.0 { self } else { other }
    }
}

// -------------------------------------------------------------------------
// Drawing
// -------------------------------------------------------------------------

impl Layer {
    /// Draw this layer at scene time `t`.
    pub fn draw(&self, canvas: &mut Canvas, ctx: &RenderCtx<'_>, t: Time, scene_duration: Time) -> Result<()> {
        if !self.active_at(t, scene_duration) {
            return Ok(());
        }
        let state = self.motion_at(t, scene_duration);
        let alpha = state.alpha * self.opacity;
        if alpha <= 0.001 && !matches!(self.content, Content::PullUp { .. }) {
            return Ok(());
        }
        let span = self.span(scene_duration);
        let local = span.local(t);
        self.draw_content(canvas, ctx, local, &state, alpha)
    }

    fn draw_content(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        local: Time,
        state: &MotionState,
        alpha: f64,
    ) -> Result<()> {
        let frame = ctx.frame;
        match &self.content {
            Content::Solid { colour } => {
                let box_ = self.placement().resolve(&frame, (frame.w, frame.h));
                canvas.fill_rect(shift(box_, state), &Paint::Solid(colour.opacity(alpha)));
            }
            Content::Gradient { stops, angle } => {
                let box_ = shift(self.placement().resolve(&frame, (frame.w, frame.h)), state);
                let p = Paint::Linear { stops: stops.clone(), angle: *angle }.opacity(alpha);
                canvas.fill_rect(box_, &p);
            }
            Content::Scrim { height, strength, colour } => {
                canvas.scrim_bottom(*height, strength * alpha, *colour);
            }
            Content::Still { asset, fit, camera } => {
                let still = ctx.assets.still(asset)?;
                let box_ = shift_scaled(
                    self.placement().resolve(&frame, (still.width() as f64, still.height() as f64)),
                    state,
                );
                match camera {
                    Some(cam) => cam.draw(canvas, &still, local, box_, alpha),
                    None => {
                        let dst = fit.apply(still.width() as f64, still.height() as f64, &box_);
                        // Route through the camera's sampler so a plain still
                        // gets the same pyramid treatment as a moving one.
                        let vp = viewport_for_fit(&still.rect(), &box_, *fit);
                        crate::camera::draw_viewport(
                            canvas,
                            &still,
                            vp,
                            if matches!(fit, Fit::Cover | Fit::Stretch) { box_ } else { dst },
                            alpha,
                        );
                    }
                }
            }
            Content::Clip { asset, fit, start, mode, max_width, radius, border, shadow } => {
                self.draw_clip(canvas, ctx, local, state, alpha, asset, *fit, *start, *mode, *max_width, *radius, *border, shadow.as_ref())?;
            }
            Content::Text { text, style, wrap, fit } => {
                let box_ = self.placement().resolve(&frame, (frame.w * 0.8, frame.h * 0.3));
                self.draw_text_block(canvas, ctx, text, style, box_, *wrap, *fit, state, alpha, local);
            }
            Content::Title { text, subtitle, style, subtitle_style } => {
                self.draw_title(canvas, ctx, text, subtitle.as_deref(), style.as_ref(), subtitle_style.as_ref(), state, alpha, local);
            }
            Content::LowerThird { text, detail, accent, style, detail_style } => {
                self.draw_lower_third(canvas, ctx, text, detail.as_deref(), *accent, style.as_ref(), detail_style.as_ref(), state, alpha);
            }
            Content::Counter { spec, label, style, label_style } => {
                self.draw_counter(canvas, ctx, spec, label.as_deref(), style.as_ref(), label_style.as_ref(), state, alpha, local);
            }
            Content::Callout { spec, style, detail_style } => {
                self.draw_callout(canvas, ctx, spec, style.as_ref(), detail_style.as_ref(), alpha, local);
            }
            Content::PullUp { spec, style } => {
                self.draw_pull_up(canvas, ctx, spec, style.as_ref(), state, alpha);
            }
        }
        Ok(())
    }

    #[allow(clippy::too_many_arguments)]
    fn draw_clip(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        local: Time,
        state: &MotionState,
        alpha: f64,
        asset: &str,
        fit: Fit,
        start: Time,
        mode: ClipLoop,
        max_width: u32,
        radius: f64,
        border: Option<(Color, f64)>,
        shadow: Option<&Shadow>,
    ) -> Result<()> {
        let clip = ctx.assets.clip(asset, ctx.fps, max_width, None)?;
        let (cw, ch) = clip.size();
        let box_ = shift_scaled(self.placement().resolve(&ctx.frame, (cw as f64, ch as f64)), state);
        let Some(frame_px) = clip.frame_at(local.as_secs() + start.as_secs(), mode) else {
            return Ok(());
        };
        let dst = fit.apply(cw as f64, ch as f64, &box_);

        if let Some(sh) = shadow {
            draw_rect_shadow(canvas, dst, radius, sh, alpha);
        }
        if radius > 0.5 {
            if let Some(path) = crate::canvas::round_rect_path(dst, radius)
                && let Some(mut mask) = tiny_skia::Mask::new(canvas.width(), canvas.height())
            {
                mask.fill_path(&path, tiny_skia::FillRule::Winding, true, tiny_skia::Transform::identity());
                canvas.draw_pixmap_masked(frame_px, dst, alpha, &mask);
            }
        } else {
            canvas.draw_pixmap_rect(frame_px, dst, alpha, tiny_skia::BlendMode::SourceOver);
        }
        if let Some((c, w)) = border {
            canvas.stroke_round_rect(dst, radius, w, &Paint::Solid(c.opacity(alpha)));
        }
        Ok(())
    }

    #[allow(clippy::too_many_arguments)]
    fn draw_text_block(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        text: &str,
        style: &TextStyle,
        box_: Rect,
        wrap: f64,
        fit: bool,
        state: &MotionState,
        alpha: f64,
        local: Time,
    ) {
        let scaled = TextStyle { size: style.size * state.scale, ..style.clone() };
        let layout = if fit {
            TextLayout::fit(ctx.fonts, text, &scaled, box_)
        } else {
            TextLayout::build(ctx.fonts, text, &scaled, Some(box_.w * wrap))
        };
        let Some(layout) = layout else { return };
        let origin = align_in(&box_, &layout, style.align, &self.placement());
        self.draw_layout(canvas, ctx, &layout, &scaled, origin, state, alpha, local);
    }

    /// Draw a layout, applying per-character staggering when the motion asks
    /// for it.
    #[allow(clippy::too_many_arguments)]
    fn draw_layout(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        layout: &TextLayout,
        style: &TextStyle,
        origin: (f64, f64),
        state: &MotionState,
        alpha: f64,
        local: Time,
    ) {
        let origin = (origin.0 + state.dx, origin.1 + state.dy);
        let staggered = self
            .enter
            .filter(|m| {
                matches!(
                    m.kind,
                    crate::motion::MotionKind::Chars { .. } | crate::motion::MotionKind::Words { .. }
                )
            })
            .map(|m| (m, self.exit));

        match staggered {
            None => crate::text::draw(canvas, ctx.fonts, layout, style, origin, alpha, None),
            Some((enter, exit)) => {
                let units = stagger_units(layout, enter.kind);
                let n = units.len().max(1);
                let elapsed = local.as_secs();
                let span = self.span(Time(f64::MAX / 4.0));
                let exit_start = exit.map(|e| span.duration.as_secs() - e.duration.as_secs());
                let f = |gi: usize, _cluster: u32| -> (f64, f64, f64, f64) {
                    let unit = *units.get(gi).unwrap_or(&0);
                    let s = match (exit, exit_start) {
                        (Some(e), Some(start)) if elapsed >= start => {
                            e.exit_state_for(elapsed - start, unit, n)
                        }
                        _ => enter.enter_state_for(elapsed, unit, n),
                    };
                    (s.dx, s.dy, s.scale, s.alpha)
                };
                // The block-level alpha is already inside the per-glyph state,
                // so pass the layer's own constant opacity only.
                crate::text::draw(
                    canvas,
                    ctx.fonts,
                    layout,
                    style,
                    origin,
                    self.opacity,
                    Some(&GlyphTransform { f: &f }),
                );
            }
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn draw_title(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        text: &str,
        subtitle: Option<&str>,
        style: Option<&TextStyle>,
        sub_style: Option<&TextStyle>,
        state: &MotionState,
        alpha: f64,
        local: Time,
    ) {
        let theme = crate::theme::Theme::default();
        let ts = style.cloned().unwrap_or_else(|| theme.title.clone());
        let ss = sub_style.cloned().unwrap_or_else(|| theme.subtitle.clone());
        let frame = ctx.frame;
        let width = frame.w * 0.82;

        let ts_scaled = TextStyle { size: ts.size * state.scale, ..ts.clone() };
        let Some(main) = TextLayout::build(ctx.fonts, text, &ts_scaled, Some(width)) else { return };
        let sub = subtitle.and_then(|s| {
            let ss_scaled = TextStyle { size: ss.size * state.scale, ..ss.clone() };
            TextLayout::build(ctx.fonts, s, &ss_scaled, Some(width)).map(|l| (l, ss_scaled))
        });

        let gap = ts.size * 0.42;
        let total_h = main.height + sub.as_ref().map(|(l, _)| l.height + gap).unwrap_or(0.0);
        let total_w = main.width.max(sub.as_ref().map(|(l, _)| l.width).unwrap_or(0.0));
        let box_ = self.placement().resolve(&frame, (total_w, total_h));

        let cx = box_.x + box_.w / 2.0;
        let mut y = box_.y;
        let main_origin = match ts.align {
            Align::Centre => (cx - main.width / 2.0, y),
            Align::Right => (box_.right() - main.width, y),
            Align::Left => (box_.x, y),
        };
        self.draw_layout(canvas, ctx, &main, &ts_scaled, main_origin, state, alpha, local);
        y += main.height + gap;
        if let Some((l, st)) = sub {
            let o = match ss.align {
                Align::Centre => (cx - l.width / 2.0, y),
                Align::Right => (box_.right() - l.width, y),
                Align::Left => (box_.x, y),
            };
            // The standfirst trails the title slightly, which is what makes a
            // title card feel composed rather than stamped.
            let lag = MotionState { alpha: alpha * 0.94, ..*state };
            self.draw_layout(canvas, ctx, &l, &st, o, &lag, alpha, local);
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn draw_lower_third(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        text: &str,
        detail: Option<&str>,
        accent: Color,
        style: Option<&TextStyle>,
        detail_style: Option<&TextStyle>,
        state: &MotionState,
        alpha: f64,
    ) {
        let theme = crate::theme::Theme::default();
        let ts = style.cloned().unwrap_or_else(|| theme.lower_third.clone());
        let ds = detail_style.cloned().unwrap_or_else(|| theme.lower_third_detail.clone());
        let frame = ctx.frame;
        let max_w = frame.w * 0.55;

        let Some(main) = TextLayout::build(ctx.fonts, text, &ts, Some(max_w)) else { return };
        let sub = detail.and_then(|d| TextLayout::build(ctx.fonts, d, &ds, Some(max_w)));
        let gap = if sub.is_some() { ts.size * 0.30 } else { 0.0 };

        let plate = Plate::dark().accent(accent, 6.0);
        let text_w = main.width.max(sub.as_ref().map(|l| l.width).unwrap_or(0.0));
        let text_h = main.height + sub.as_ref().map(|l| l.height + gap).unwrap_or(0.0);
        let accent_w = plate.accent.map(|(_, w)| w).unwrap_or(0.0);
        let plate_w = text_w + plate.pad.0 * 2.0 + accent_w;
        let plate_h = text_h + plate.pad.1 * 2.0;

        let box_ = self.placement().resolve(&frame, (plate_w, plate_h));
        let r = Rect::new(box_.x + state.dx, box_.y + state.dy, plate_w, plate_h);
        plate.draw(canvas, r, alpha);

        let tx = r.x + accent_w + plate.pad.0;
        let mut ty = r.y + plate.pad.1;
        crate::text::draw(canvas, ctx.fonts, &main, &ts, (tx, ty), alpha, None);
        ty += main.height + gap;
        if let Some(l) = sub {
            crate::text::draw(canvas, ctx.fonts, &l, &ds, (tx, ty), alpha * 0.92, None);
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn draw_counter(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        spec: &CounterSpec,
        label: Option<&str>,
        style: Option<&TextStyle>,
        label_style: Option<&TextStyle>,
        state: &MotionState,
        alpha: f64,
        local: Time,
    ) {
        let theme = crate::theme::Theme::default();
        let ts = style.cloned().unwrap_or_else(|| theme.counter.clone());
        let ls = label_style.cloned().unwrap_or_else(|| theme.counter_label.clone());
        let text = spec.text_at(local.as_secs());

        let ts_scaled = TextStyle { size: ts.size * state.scale, ..ts.clone() };
        let Some(num) = TextLayout::build(ctx.fonts, &text, &ts_scaled, None) else { return };
        // Reserve the width of the *final* value so the block does not shuffle
        // as the number grows. Tabular digits fix the jitter within a value;
        // this fixes it between values.
        let widest = TextLayout::build(ctx.fonts, &spec.text_at(spec.over.as_secs()), &ts_scaled, None)
            .map(|l| l.width)
            .unwrap_or(num.width);
        let lab = label.and_then(|l| TextLayout::build(ctx.fonts, l, &ls, None));
        let gap = if lab.is_some() { ts.size * 0.18 } else { 0.0 };
        let total_w = widest.max(lab.as_ref().map(|l| l.width).unwrap_or(0.0));
        let total_h = num.height + lab.as_ref().map(|l| l.height + gap).unwrap_or(0.0);

        let box_ = self.placement().resolve(&ctx.frame, (total_w, total_h));
        let right_aligned = matches!(ts.align, Align::Right);
        let x = if right_aligned { box_.right() - num.width } else { box_.x };
        let (x, y) = (x + state.dx, box_.y + state.dy);
        crate::text::draw(canvas, ctx.fonts, &num, &ts_scaled, (x, y), alpha, None);
        if let Some(l) = lab {
            let lx = if right_aligned { box_.right() - l.width } else { box_.x };
            crate::text::draw(
                canvas,
                ctx.fonts,
                &l,
                &ls,
                (lx + state.dx, y + num.height + gap),
                alpha * 0.85,
                None,
            );
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn draw_callout(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        spec: &CalloutSpec,
        style: Option<&TextStyle>,
        detail_style: Option<&TextStyle>,
        alpha: f64,
        local: Time,
    ) {
        let theme = crate::theme::Theme::default();
        let ts = style.cloned().unwrap_or_else(|| theme.callout.clone());
        let ds = detail_style.cloned().unwrap_or_else(|| theme.callout_detail.clone());
        let frame = ctx.frame;
        let target = (frame.w * spec.target.0, frame.h * spec.target.1);
        let anchor = (frame.w * spec.label_at.0, frame.h * spec.label_at.1);

        // The callout draws itself on: ring, then leader, then plate. Timings
        // are fractions of the entrance so one `enter` controls the whole move.
        let dur = self.enter.map(|m| m.duration.as_secs()).unwrap_or(0.45).max(0.01);
        let t = (local.as_secs() / dur).clamp(0.0, 1.0);
        let ring_p = Easing::OutCubic.apply((t / 0.35).clamp(0.0, 1.0));
        let line_p = Easing::OutCubic.apply(((t - 0.2) / 0.5).clamp(0.0, 1.0));
        let plate_p = Easing::OutCubic.apply(((t - 0.55) / 0.45).clamp(0.0, 1.0));

        if ring_p > 0.0 {
            let r = spec.ring * ring_p;
            let paint = Paint::Solid(spec.accent.opacity(alpha * ring_p));
            let mut pb = tiny_skia::PathBuilder::new();
            pb.push_circle(target.0 as f32, target.1 as f32, r as f32);
            if let Some(p) = pb.finish() {
                canvas.stroke_path_with(&p, &paint, 3.0, Rect::centred(target.0, target.1, r * 2.0, r * 2.0));
            }
            // A solid dot at the centre reads as "this exact spot".
            let mut pb = tiny_skia::PathBuilder::new();
            pb.push_circle(target.0 as f32, target.1 as f32, (r * 0.22).max(1.5) as f32);
            if let Some(p) = pb.finish() {
                canvas.fill_path_with(&p, &paint, Rect::centred(target.0, target.1, r, r));
            }
        }

        // The leader leaves the ring's edge, not its centre.
        let (dx, dy) = (anchor.0 - target.0, anchor.1 - target.1);
        let len = dx.hypot(dy).max(1.0);
        let (ux, uy) = (dx / len, dy / len);
        let start = (target.0 + ux * spec.ring, target.1 + uy * spec.ring);
        if line_p > 0.0 {
            let end = (start.0 + ux * (len - spec.ring) * line_p, start.1 + uy * (len - spec.ring) * line_p);
            canvas.line(start.0, start.1, end.0, end.1, 2.5, &Paint::Solid(spec.accent.opacity(alpha * 0.95)));
        }

        if plate_p > 0.0 {
            let max_w = frame.w * 0.34;
            let Some(main) = TextLayout::build(ctx.fonts, &spec.text, &ts, Some(max_w)) else { return };
            let sub = spec.detail.as_ref().and_then(|d| TextLayout::build(ctx.fonts, d, &ds, Some(max_w)));
            let gap = if sub.is_some() { ts.size * 0.24 } else { 0.0 };
            let tw = main.width.max(sub.as_ref().map(|l| l.width).unwrap_or(0.0));
            let th = main.height + sub.as_ref().map(|l| l.height + gap).unwrap_or(0.0);
            let plate = Plate { pad: (22.0, 14.0), radius: 8.0, ..Plate::dark() }.accent(spec.accent, 4.0);
            let pw = tw + plate.pad.0 * 2.0 + 4.0;
            let ph = th + plate.pad.1 * 2.0;
            // Grow away from the target, so the plate never covers the thing
            // it is pointing at.
            let px = if ux >= 0.0 { anchor.0 } else { anchor.0 - pw };
            let py = anchor.1 - ph / 2.0;
            let a = alpha * plate_p;
            plate.draw(canvas, Rect::new(px, py, pw, ph), a);
            let tx = px + 4.0 + plate.pad.0;
            let mut ty = py + plate.pad.1;
            crate::text::draw(canvas, ctx.fonts, &main, &ts, (tx, ty), a, None);
            ty += main.height + gap;
            if let Some(l) = sub {
                crate::text::draw(canvas, ctx.fonts, &l, &ds, (tx, ty), a * 0.9, None);
            }
        }
    }

    fn draw_pull_up(
        &self,
        canvas: &mut Canvas,
        ctx: &RenderCtx<'_>,
        spec: &PullUpSpec,
        style: Option<&TextStyle>,
        state: &MotionState,
        alpha: f64,
    ) {
        let frame = ctx.frame;
        // Snapshot what is underneath: this layer lifts the *frame*, so it
        // works over anything without knowing what drew it.
        let beneath = canvas.clone();
        let src = Rect::new(
            frame.w * spec.region.0,
            frame.h * spec.region.1,
            frame.w * spec.region.2,
            frame.h * spec.region.3,
        );
        if src.w <= 1.0 || src.h <= 1.0 {
            return;
        }

        // Progress drives everything so a single `enter` animates the lift.
        let p = if state.alpha <= 0.0 { 0.0 } else { state.alpha };
        canvas.dim(spec.dim * p * self.opacity, Color::rgb(4, 6, 10));

        let dest = match spec.to {
            Some((fx, fy, fw, fh)) => Rect::new(frame.w * fx, frame.h * fy, frame.w * fw, frame.h * fh)
                .to_aspect(src.aspect()),
            None => {
                // Default: 2.1x, centred, clamped to the frame with a margin.
                let k = 2.1f64.min((frame.w * 0.78) / src.w).min((frame.h * 0.72) / src.h);
                let (cx, cy) = frame.centre();
                Rect::centred(cx, cy, src.w * k, src.h * k)
            }
        };
        // Travel from where it was to where it goes.
        let cur = src.lerp(&dest, p).to_aspect(src.aspect());
        let cur = Rect::centred(
            cur.centre().0,
            cur.centre().1,
            cur.w * state.scale.max(0.01),
            cur.h * state.scale.max(0.01),
        );

        if spec.tether && p > 0.05 && p < 0.999 {
            canvas.stroke_round_rect(
                src,
                spec.radius * 0.6,
                1.5,
                &Paint::Solid(spec.border.opacity(alpha * 0.45 * (1.0 - p))),
            );
        }

        draw_rect_shadow(
            canvas,
            cur,
            spec.radius,
            &Shadow { colour: Color::rgba(0, 0, 0, 190), blur: 34.0, dx: 0.0, dy: 14.0 },
            alpha,
        );

        // Re-draw the snapshot region, enlarged.
        if let Some(path) = crate::canvas::round_rect_path(cur, spec.radius)
            && let Some(mut mask) = tiny_skia::Mask::new(canvas.width(), canvas.height())
        {
            mask.fill_path(&path, tiny_skia::FillRule::Winding, true, tiny_skia::Transform::identity());
            let sx = (cur.w / src.w) as f32;
            let sy = (cur.h / src.h) as f32;
            let tf = tiny_skia::Transform::from_row(
                sx, 0.0, 0.0, sy,
                (cur.x - src.x * sx as f64) as f32,
                (cur.y - src.y * sy as f64) as f32,
            );
            let paint = tiny_skia::PixmapPaint {
                opacity: alpha as f32,
                blend_mode: tiny_skia::BlendMode::SourceOver,
                quality: if sx >= 1.5 { tiny_skia::FilterQuality::Nearest } else { tiny_skia::FilterQuality::Bilinear },
            };
            canvas.pixmap.draw_pixmap(0, 0, beneath.as_ref(), &paint, tf, Some(&mask));
        }
        if spec.border_width > 0.0 {
            canvas.stroke_round_rect(
                cur,
                spec.radius,
                spec.border_width,
                &Paint::Solid(spec.border.opacity(alpha)),
            );
        }

        if let Some(label) = &spec.label
            && p > 0.35
        {
            let theme = crate::theme::Theme::default();
            let ts = style.cloned().unwrap_or_else(|| theme.callout.clone());
            let a = alpha * ((p - 0.35) / 0.65).clamp(0.0, 1.0);
            if let Some(l) = TextLayout::build(ctx.fonts, label, &ts, Some(cur.w)) {
                let plate = Plate { pad: (20.0, 12.0), radius: 8.0, ..Plate::dark() };
                let pw = l.width + plate.pad.0 * 2.0;
                let ph = l.height + plate.pad.1 * 2.0;
                let px = cur.centre().0 - pw / 2.0;
                let py = cur.bottom() + 18.0;
                plate.draw(canvas, Rect::new(px, py, pw, ph), a);
                crate::text::draw(
                    canvas,
                    ctx.fonts,
                    &l,
                    &ts,
                    (px + plate.pad.0, py + plate.pad.1),
                    a,
                    None,
                );
            }
        }
    }
}

/// The viewport of a still that a fit mode implies.
fn viewport_for_fit(src: &Rect, box_: &Rect, fit: Fit) -> Rect {
    match fit {
        // Cover crops the source to the box's aspect.
        Fit::Cover => src.to_aspect(box_.aspect()).clamp_within(src).inset(0.0),
        _ => *src,
    }
}

fn shift(r: Rect, s: &MotionState) -> Rect {
    Rect { x: r.x + s.dx, y: r.y + s.dy, ..r }
}

fn shift_scaled(r: Rect, s: &MotionState) -> Rect {
    let (cx, cy) = r.centre();
    Rect::centred(cx + s.dx, cy + s.dy, r.w * s.scale, r.h * s.scale)
}

fn align_in(box_: &Rect, layout: &TextLayout, align: Align, placement: &Placement) -> (f64, f64) {
    // An anchored placement has already been sized to the text, so its box is
    // the answer; an explicit box needs the text aligned inside it.
    if matches!(placement, Placement::Anchored { .. }) {
        return (box_.x, box_.y);
    }
    let x = match align {
        Align::Left => box_.x,
        Align::Centre => box_.x + (box_.w - layout.width) / 2.0,
        Align::Right => box_.right() - layout.width,
    };
    (x, box_.y)
}

/// A blurred rounded-rect shadow under `r`.
fn draw_rect_shadow(canvas: &mut Canvas, r: Rect, radius: f64, sh: &Shadow, alpha: f64) {
    let pad = (sh.blur * 3.0).ceil();
    let (w, h) = ((r.w + pad * 2.0).ceil() as u32, (r.h + pad * 2.0).ceil() as u32);
    if w == 0 || h == 0 || w > 8192 || h > 8192 {
        return;
    }
    let Some(mut sp) = tiny_skia::Pixmap::new(w, h) else { return };
    if let Some(p) = crate::canvas::round_rect_path(Rect::new(pad, pad, r.w, r.h), radius) {
        let mut sk = tiny_skia::Paint { anti_alias: true, ..Default::default() };
        sk.shader = tiny_skia::Shader::SolidColor(tiny_skia::Color::BLACK);
        sp.fill_path(&p, &sk, tiny_skia::FillRule::Winding, tiny_skia::Transform::identity(), None);
    }
    crate::canvas::blur_alpha(&mut sp, sh.blur);
    let Some(mut mask) = tiny_skia::Mask::new(w, h) else { return };
    {
        let m = mask.data_mut();
        for (i, px) in sp.pixels().iter().enumerate() {
            m[i] = px.alpha();
        }
    }
    let Some(mut tint) = tiny_skia::Pixmap::new(w, h) else { return };
    tint.fill(sh.colour.to_skia());
    tint.apply_mask(&mask);
    canvas.draw_pixmap_rect(
        tint.as_ref(),
        Rect::new(r.x - pad + sh.dx, r.y - pad + sh.dy, w as f64, h as f64),
        alpha,
        tiny_skia::BlendMode::SourceOver,
    );
}

/// Map each glyph to the stagger unit it belongs to: itself, or its word.
fn stagger_units(layout: &TextLayout, kind: crate::motion::MotionKind) -> Vec<usize> {
    let mut out = Vec::with_capacity(layout.glyph_count);
    match kind {
        crate::motion::MotionKind::Words { .. } => {
            let mut word = 0usize;
            for line in &layout.lines {
                let bytes = line.text.as_bytes();
                for g in &line.glyphs {
                    // A cluster landing on whitespace ends the current word.
                    let is_space = bytes
                        .get(g.cluster as usize)
                        .map(|b| b.is_ascii_whitespace())
                        .unwrap_or(false);
                    if is_space {
                        word += 1;
                    }
                    out.push(word);
                }
                word += 1;
            }
        }
        _ => {
            for (i, _) in (0..layout.glyph_count).enumerate() {
                out.push(i);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counter_counts_and_holds() {
        let c = CounterSpec::new(0.0, 600.0, 2.0);
        assert_eq!(c.text_at(0.0), "0");
        assert_eq!(c.text_at(2.0), "600");
        assert_eq!(c.text_at(99.0), "600", "must hold at the end");
        let mid = c.value_at(1.0);
        assert!(mid > 0.0 && mid < 600.0, "mid {mid}");
    }

    #[test]
    fn counter_groups_thousands_and_takes_affixes() {
        let c = CounterSpec::new(0.0, 12345.0, 1.0).suffix(" runs").prefix("~");
        assert_eq!(c.text_at(1.0), "~12\u{202f}345 runs");
        let plain = CounterSpec { group: false, ..CounterSpec::new(0.0, 12345.0, 1.0) };
        assert_eq!(plain.text_at(1.0), "12345");
    }

    #[test]
    fn counter_decimals() {
        let c = CounterSpec::new(0.0, 99.5, 1.0).decimals(1).suffix("%");
        assert_eq!(c.text_at(1.0), "99.5%");
    }

    #[test]
    fn layer_span_defaults_to_the_rest_of_the_scene() {
        let l = Layer::text("x").from(2.0);
        let s = l.span(Time(10.0));
        assert_eq!(s.start, Time(2.0));
        assert_eq!(s.duration, Time(8.0));
        assert!(l.active_at(Time(5.0), Time(10.0)));
        assert!(!l.active_at(Time(1.0), Time(10.0)));
    }

    #[test]
    fn explicit_duration_wins() {
        let l = Layer::text("x").from(1.0).lasting(2.0);
        assert!(l.active_at(Time(2.0), Time(10.0)));
        assert!(!l.active_at(Time(3.5), Time(10.0)));
    }

    #[test]
    fn exit_overrides_enter_where_they_overlap() {
        // A 1s layer with a 0.8s entrance and a 0.8s exit: at 0.9s the exit is
        // what should be running.
        let l = Layer::text("x")
            .lasting(1.0)
            .entering(Motion::fade(0.8))
            .exiting(Motion::fade(0.8));
        let s = l.motion_at(Time(0.95), Time(4.0));
        assert!(s.alpha < 0.5, "exit should be well underway: {s:?}");
    }

    #[test]
    fn placement_fractions_scale_with_the_frame() {
        let f = Rect::from_size(1920.0, 1080.0);
        let r = Placement::frac(0.25, 0.5, 0.5, 0.25).resolve(&f, (0.0, 0.0));
        assert_eq!((r.x, r.y, r.w, r.h), (480.0, 540.0, 960.0, 270.0));
    }

    #[test]
    fn placement_reads_as_a_bare_word() {
        let p: Placement = serde_json::from_str("\"centre\"").unwrap();
        assert_eq!(p, Placement::Anchored { anchor: Anchor::Centre, pad: default_pad() });
        assert_eq!(serde_json::from_str::<Placement>("\"full\"").unwrap(), Placement::Full);
        // And writes back as one.
        assert_eq!(serde_json::to_string(&Placement::Full).unwrap(), "\"full\"");
    }

    #[test]
    fn placement_reads_as_numbers_when_it_needs_to() {
        let f: Placement =
            serde_json::from_str(r#"{"fx":0.1,"fy":0.2,"fw":0.3,"fh":0.4}"#).unwrap();
        assert_eq!(f, Placement::Frac { fx: 0.1, fy: 0.2, fw: 0.3, fh: 0.4 });
        let a: Placement = serde_json::from_str(r#"{"anchor":"bottom-left","pad":20}"#).unwrap();
        assert_eq!(a, Placement::Anchored { anchor: Anchor::BottomLeft, pad: 20.0 });
        let r: Placement = serde_json::from_str(r#"{"x":1,"y":2,"w":3,"h":4}"#).unwrap();
        assert_eq!(r, Placement::Rect { x: 1.0, y: 2.0, w: 3.0, h: 4.0 });
    }

    #[test]
    fn content_without_a_placement_lands_where_it_belongs() {
        let solid: Layer = serde_json::from_str(r##"{"type":"solid","colour":"#fff"}"##).unwrap();
        assert_eq!(solid.placement(), Placement::Full);
        // These are the ones that bite: a lower-third written in JSON with no
        // placement must still land bottom-left, not at the origin.
        let lt: Layer = serde_json::from_str(r#"{"type":"lower-third","text":"x"}"#).unwrap();
        assert_eq!(lt.placement(), Placement::Anchored { anchor: Anchor::BottomLeft, pad: 96.0 });
        let c: Layer =
            serde_json::from_str(r#"{"type":"counter","count":{"from":0,"to":1,"over":1}}"#)
                .unwrap();
        assert_eq!(c.placement(), Placement::Anchored { anchor: Anchor::TopRight, pad: 72.0 });
        let t: Layer = serde_json::from_str(r#"{"type":"title","text":"x"}"#).unwrap();
        assert_eq!(t.placement(), Placement::Anchored { anchor: Anchor::Centre, pad: 72.0 });
    }

    #[test]
    fn the_json_and_the_builder_agree_on_placement() {
        let built = Layer::lower_third("x");
        let parsed: Layer = serde_json::from_str(r#"{"type":"lower-third","text":"x"}"#).unwrap();
        assert_eq!(built.placement(), parsed.placement());
        assert_eq!(Layer::counter(0.0, 1.0, 1.0).placement(), Layer::new(
            Content::Counter { spec: CounterSpec::new(0.0, 1.0, 1.0), label: None, style: None, label_style: None }
        ).placement());
    }

    #[test]
    fn an_explicit_placement_overrides_the_default() {
        let l = Layer::lower_third("x").at(Anchor::TopRight);
        assert_eq!(l.placement(), Placement::Anchored { anchor: Anchor::TopRight, pad: 72.0 });
    }

    #[test]
    fn a_counter_keeps_its_value_and_its_time_apart() {
        let l: Layer = serde_json::from_str(
            r#"{"type":"counter","count":{"from":0,"to":600,"over":2},"from":1.5}"#,
        )
        .unwrap();
        assert_eq!(l.from, Time(1.5), "the layer starts at 1.5s");
        let Content::Counter { spec, .. } = &l.content else { panic!() };
        assert_eq!(spec.from, 0.0, "and counts from zero");
        assert_eq!(spec.to, 600.0);
    }

    #[test]
    fn layers_round_trip_through_json() {
        let l = Layer::lower_third("Kanto").detail("226 maps").accent(Color::rgb(1, 2, 3)).from(1.5);
        let s = serde_json::to_string(&l).unwrap();
        let back: Layer = serde_json::from_str(&s).unwrap();
        assert_eq!(back, l);
        assert!(s.contains("lower-third"), "{s}");
    }

    #[test]
    fn word_staggering_groups_glyphs_by_word() {
        let db = FontDb::shared();
        let st = TextStyle::default().size(40.0);
        let layout = TextLayout::build(db, "one two", &st, None).unwrap();
        let units = stagger_units(layout_ref(&layout), crate::motion::MotionKind::Words { stagger: 0.1, rise: 10.0 });
        assert_eq!(units.len(), layout.glyph_count);
        assert_eq!(units[0], 0, "first glyph in word 0");
        assert!(*units.last().unwrap() > 0, "last glyph in a later word");
    }

    fn layout_ref(l: &TextLayout) -> &TextLayout {
        l
    }
}
