//! ShowReel — a declarative toolset for demo, explainer and animation films.
//!
//! A film is a **data description** — a serde tree of scenes, layers and
//! transitions — rendered deterministically to frames and handed to ffmpeg.
//! The Rust builders are ergonomic sugar over exactly the same types, so a
//! film can be written by hand, generated by a program, or loaded from JSON,
//! and none of those is a special case.
//!
//! ```no_run
//! use showreel::prelude::*;
//!
//! let film = Film::new(1920, 1080, 60.0)
//!     .title("A short reel")
//!     .open(
//!         Scene::new(4.0)
//!             .named("title")
//!             .layer(Layer::title("AI plays Pokemon")
//!                 .subtitle("600 cold boots, one cartridge")
//!                 .entering(Motion::chars(0.5, 0.022))),
//!     )
//!     .then(
//!         Transition::dissolve(0.8),
//!         Scene::new(6.0)
//!             .named("the map")
//!             .layer(Layer::camera("world.png",
//!                 Camera::pull_back(Framing::at(0.15, 0.80, 288.0), 5.0)))
//!             .layer(Layer::lower_third("Kanto").detail("226 maps").from(1.0)),
//!     );
//!
//! assert!(film.validate().is_empty());
//! std::fs::write("reel.film.json", film.to_json().unwrap()).unwrap();
//! ```
//!
//! Then `showreel render reel.film.json -o reel.mp4`.
pub mod canvas;
pub mod color;
pub mod ease;
pub mod expr;
pub mod geom;
pub mod time;
pub mod assets;
pub mod camera;
pub mod text;
pub mod transition;
pub mod motion;
pub mod layer;
pub mod chart;
pub mod plugin;
pub mod grade;
pub mod theme;
pub mod timeline;
pub mod scale;
pub mod render;
pub mod audio;
// Pure DSP (sample buffers, no ffmpeg, no filesystem), so — unlike `encode` —
// it stays available on every target, wasm included. See its module docs.
pub mod music;
// Shells out to ffmpeg (`std::process::Command`), which has no browser
// story — see src/wasm.rs's module docs — so it is native-only.
#[cfg(not(target_arch = "wasm32"))]
pub mod encode;
pub mod preview;
pub mod prelude;
#[cfg(feature = "studio")]
pub mod studio;
#[cfg(feature = "mcp")]
pub mod mcp;
// The .srclip container is used natively by `showreel web-pack` (encode) and
// in the browser by src/wasm.rs (decode), so it is not itself wasm32-only.
#[cfg(feature = "wasm")]
pub mod webclip;
#[cfg(all(feature = "wasm", target_arch = "wasm32"))]
pub mod wasm;
